apiVersion: v1
kind: Service
metadata:
  name: check-connection-wasm
spec:
  selector:
    app: check-connection-wasm
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1234
      nodePort: 30000
